seed: -1
dataset: MCAC-M1
test_split: test
resume_path: "checkpoints/model_chkpt.ckpt"

MCAC_crop_size: 672
MCAC_occ_limit: 70
img_channels: 3

counting_backbone: "vit_dino"
counting_head: "5_32"
upsample_padding_mode: 'replicate' # 'zeros', 'reflect', 'replicate'

matching_type: density # no_match, count, density
matcher_cost_power: 2
normalize_matching: True

gtd_scale: 400


eval_batch_size: 2
val_every: 1

max_epochs: 0